/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClipboardSaverPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
function getElectronClipboard() {
  const req = window.require;
  if (typeof req !== "function") return null;
  const electron = req("electron");
  if (electron?.clipboard) return electron.clipboard;
  if (electron?.remote?.clipboard) return electron.remote.clipboard;
  return null;
}
var electronClipboard = getElectronClipboard();
var DEFAULT_SETTINGS = {
  enabled: true,
  includeTimestamp: true,
  separator: "---"
};
var ClipboardSaverPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.textChangedHandler = null;
    /** 上一次已写入的内容，用于去重，避免同一次复制触发多次写入 */
    this.lastContent = "";
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ClipboardSaverSettingTab(this.app, this));
    if (electronClipboard && this.settings.enabled) {
      this.startMonitoring();
    }
    this.addCommand({
      id: "toggle-clipboard-monitor",
      name: "\u5207\u6362\u526A\u8D34\u677F\u81EA\u52A8\u76D1\u542C\uFF08\u684C\u9762\u7AEF\uFF09",
      callback: async () => {
        if (!electronClipboard) {
          new import_obsidian.Notice("Clipboard Saver\uFF1A\u79FB\u52A8\u7AEF\u4E0D\u652F\u6301\u81EA\u52A8\u76D1\u542C\uFF0C\u8BF7\u4F7F\u7528\u201C\u4FDD\u5B58\u5F53\u524D\u526A\u8D34\u677F\u5185\u5BB9\u201D\u547D\u4EE4\u3002");
          return;
        }
        this.settings.enabled = !this.settings.enabled;
        await this.saveSettings();
        if (this.settings.enabled) {
          this.startMonitoring();
          new import_obsidian.Notice("Clipboard Saver\uFF1A\u5DF2\u5F00\u542F\u81EA\u52A8\u76D1\u542C");
        } else {
          this.stopMonitoring();
          new import_obsidian.Notice("Clipboard Saver\uFF1A\u5DF2\u6682\u505C\u81EA\u52A8\u76D1\u542C");
        }
      }
    });
    this.addCommand({
      id: "save-clipboard-now",
      name: "\u4FDD\u5B58\u5F53\u524D\u526A\u8D34\u677F\u5185\u5BB9",
      callback: () => {
        void this.handleClipboardChange(true);
      }
    });
  }
  onunload() {
    this.stopMonitoring();
  }
  /** 桌面端：开始监听 Electron 剪贴板变化 */
  startMonitoring() {
    if (!electronClipboard) return;
    if (this.textChangedHandler) return;
    this.textChangedHandler = () => {
      void this.handleClipboardChange(false);
    };
    electronClipboard.on("text-changed", this.textChangedHandler);
  }
  stopMonitoring() {
    if (this.textChangedHandler && electronClipboard) {
      electronClipboard.removeListener(
        "text-changed",
        this.textChangedHandler
      );
      this.textChangedHandler = null;
    }
  }
  /**
   * 读取系统剪贴板文本（跨端）：
   * 优先 navigator.clipboard（手机/桌面通用，需用户手势），
   * 失败或不可用时退回 Electron（桌面后台更稳）。
   */
  async readClipboard() {
    const clip = typeof navigator !== "undefined" ? navigator.clipboard : void 0;
    try {
      if (clip && clip.readText) {
        const text = await clip.readText();
        if (text) return text;
      }
    } catch {
    }
    if (electronClipboard) {
      return electronClipboard.readText();
    }
    return "";
  }
  /**
   * 剪贴板变化 / 手动触发时的处理逻辑。
   * @param force 为 true 时（手动命令）跳过内容去重，强制写入
   */
  async handleClipboardChange(force = false) {
    const content = await this.readClipboard();
    if (!content) {
      new import_obsidian.Notice("Clipboard Saver\uFF1A\u526A\u8D34\u677F\u4E3A\u7A7A\u6216\u8BFB\u53D6\u88AB\u62D2\u7EDD\uFF08\u8BF7\u68C0\u67E5\u526A\u8D34\u677F\u6743\u9650\uFF09\u3002");
      return;
    }
    if (!force && content === this.lastContent) return;
    this.lastContent = content;
    const activeFile = this.app.workspace.getActiveFile();
    if (!(activeFile instanceof import_obsidian.TFile) || activeFile.extension !== "md") {
      new import_obsidian.Notice("Clipboard Saver\uFF1A\u5F53\u524D\u6253\u5F00\u7684\u4E0D\u662F Markdown \u7B14\u8BB0\uFF0C\u5DF2\u5FFD\u7565");
      return;
    }
    const lines = [this.settings.separator];
    if (this.settings.includeTimestamp) {
      lines.push(this.formatTimestamp(/* @__PURE__ */ new Date()));
    }
    lines.push(content);
    lines.push(this.settings.separator);
    const block = "\n" + lines.join("\n") + "\n";
    await this.app.vault.append(activeFile, block);
    new import_obsidian.Notice("Clipboard Saver\uFF1A\u5DF2\u5199\u5165\u526A\u8D34\u677F\u5185\u5BB9");
  }
  formatTimestamp(date) {
    const pad = (n) => n.toString().padStart(2, "0");
    const y = date.getFullYear();
    const m = pad(date.getMonth() + 1);
    const d = pad(date.getDate());
    const hh = pad(date.getHours());
    const mm = pad(date.getMinutes());
    const ss = pad(date.getSeconds());
    return `${y}-${m}-${d} ${hh}:${mm}:${ss}`;
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var ClipboardSaverSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u76D1\u542C\uFF08\u4EC5\u684C\u9762\u7AEF\uFF09").setDesc(
      "\u684C\u9762\u7AEF\u5F00\u542F\u540E\uFF0C\u590D\u5236\u5373\u81EA\u52A8\u8FFD\u52A0\u5230\u5F53\u524D\u7B14\u8BB0\u3002\u79FB\u52A8\u7AEF\u65E0\u6B64\u80FD\u529B\uFF0C\u8BF7\u6539\u7528\u547D\u4EE4\u201C\u4FDD\u5B58\u5F53\u524D\u526A\u8D34\u677F\u5185\u5BB9\u201D\u3002"
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.enabled).onChange(async (v) => {
        this.plugin.settings.enabled = v;
        await this.plugin.saveSettings();
        if (!electronClipboard) return;
        if (v) this.plugin.startMonitoring();
        else this.plugin.stopMonitoring();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5199\u5165\u65F6\u95F4\u6233").setDesc("\u5728\u526A\u8D34\u677F\u5185\u5BB9\u4E0A\u65B9\u9644\u52A0\u5F53\u524D\u65F6\u95F4").addToggle(
      (t) => t.setValue(this.plugin.settings.includeTimestamp).onChange(async (v) => {
        this.plugin.settings.includeTimestamp = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5206\u9694\u7B26").setDesc("\u7528\u4E8E\u5305\u88F9\u526A\u8D34\u677F\u5185\u5BB9\u7684\u5206\u9694\u7EBF\u6587\u672C").addText(
      (t) => t.setValue(this.plugin.settings.separator).onChange(async (v) => {
        this.plugin.settings.separator = v;
        await this.plugin.saveSettings();
      })
    );
  }
};
